### ISSUE TITLE
Goblet scraper keywords are URLs

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS_scrapers#16]
Should just be the terms

Also `scientific_topic_names` are now missing

**Comment by fbacall** [comment]
Google's structured data testing tool doesn't play nice when given a GOBLET URL, but works fine if you paste in the HTML

**Comment by njall** [comment]
https://github.com/ElixirTeSS/TeSS_scrapers/commit/08a7d5a782b8754c49353d5644ad0c9339fe03b9
