### ISSUE TITLE
Re-implement GOBLET API scraper

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS_scrapers#20]
We need to bring back the old GOBLET API as the RDFa one is insufficuent
github.com/ElixirUK/TeSS_scrapers/blob/9f22a17065e0d2c97f9023568e69979f8ae68dd3/unrefactored_scrapers/goblet_api_scraper.rb 
It needs putting in the new scraper framework format

**Comment by knirirr** [comment]
I've re-added this in the new format but I've not yet enabled it in run_scrapers.rb (please go ahead if you still want to use it).
