### ISSUE TITLE
Send a notification e-mail if scrapers do not run

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS_scrapers#31]
If for some reason the scraper fails to run, send out an e-mail informing tess info mailing / niall

**Comment by knirirr** [comment]
I've modified run_scrapers.rb so it will email a list of failed scripts after running. Also, I've put script on the production server which will email if for some reason the cron job fails to run the scrapers. 
If this is OK and working then please close - thanks.

**Comment by knirirr** [comment]
This still failed as the FROM header wasn't set correctly. I'll retry tonight.

**Comment by knirirr** [comment]
Now working.
