### ISSUE TITLE
BiVi scraper

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS_scrapers#34]
BiVi - Bioinformatics Visualization - have made some RSS feeds for us. These are the three RSS feeds listed below: one event, one material, and one to be ignored for now as it seems more to be tools than TeSS content. The \<description>\</description> element has encoded some attributes within the text in the format

 #field: \<value>

So these will need to be regexed out, and some are lists (e.g. keywords) so will need to be split by commas.
 
Ignore: http://bivi.co/visualisation-feed
Materials: http://bivi.co/presentation-feed
Events: http://bivi.co/event-feed

Text for content provider should be 

About BiVi

The Biological Visualisation Network (BiVi) provides a forum for dissemination, training and discussion for life-scientists to discover and promote complex data visualisation ideas and solutions. BiVi, funded by the BBSRC, is a central resource for information on bio-visualisation and is supplemented with annual meetings for networking and educational purposes, focussed around emerging trends in visualisation and challenges facing biology.

**Comment by knirirr** [comment]
These have been added, though I've not set the events scraper to run as I'm not sure yet how to deal with the location. In any case they only have 2 future and 8-9 past events.

**Comment by knirirr** [comment]
It looks as if these are running so this ticket may presumably be closed.
