### ISSUE TITLE
Prevent needless updates

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS_scrapers#40]
Some scrapers randomly change the order of certain array fields, causing an activity log to be generated even though nothing really changed.

See: https://tess.elixir-europe.org/materials/key-terms-a-learning-game-for-conceptual-consolidation#activity_log

```
 scraper updated "Key-terms", a learning game for conceptual consolidation at 2017-10-05 03:10:19 UTC.
changed Remote updated date to: 2017-10-05
scraper updated "Key-terms", a learning game for conceptual consolidation at 2017-10-04 03:10:04 UTC.
changed Target audience to: ["Trainers", "Educators", "Ontologists"]
changed Remote updated date to: 2017-10-04
scraper updated "Key-terms", a learning game for conceptual consolidation at 2017-10-03 09:15:05 UTC.
changed Target audience to: ["Educators", "Trainers", "Ontologists"]
changed Remote updated date to: 2017-10-03
scraper updated "Key-terms", a learning game for conceptual consolidation at 2017-09-28 03:21:47 UTC.
changed Target audience to: ["Ontologists", "Trainers", "Educators"]
changed Remote updated date to: 2017-09-28
```

**Comment by knirirr** [comment]
I wonder if it would be worth fixing this in the model within TeSS. For example, one could use:

    def target_audience=(value)
        super(value.sort!)
    end

    #.... more setters for other fields

...which would make sure that every time a script set such a field it would always end up in the same order. Or, with a callback:

    before_save :fix_field_order

    def fix_field_order
        target_audience.sort!
        #.... similar lines for other fields
    end

...for the same effect.

If this would be acceptable I could proceed.
