### ISSUE TITLE
Update Elixir Portugal scraper

### ISSUE THREAD

**Issue by aapaolaza** [ElixirTeSS/TeSS_scrapers#84]
portugal_events_scraper.rb

New URL: https://biodata.pt/events

The schema node was generated through Drupal, and doesn't follow the traditional structure, so we'll have to account for that.

**Comment by christopherchild** [comment]
Fix from Aitor: [https://github.com/ElixirTeSS/TeSS_scrapers/commits/fix_portugal_scraper](https://github.com/ElixirTeSS/TeSS_scrapers/commits/fix_portugal_scraper)

**Comment by christopherchild** [comment]
I will test this and ensure we are not using the "past-events" URL.
